using System;
using ExerciciosLogica;

//Soma.Main(args);
//Subtracao.Main(args);
//Multiplicacao.Main(args);
//Divisao.Main(args);
//Sucessor.Main(args);
//Antecessor.Main(args);
//Matematica.Main(args);
//Se.Main(args);
//SeSenao.Main(args);
//Retangulo.Main(args);
//Triangulo.Main(args);
//Circulo.Main(args);
//Quadrado.Main(args);
//Losango.Main(args);
//Hexagono.Main(args);
//Trapezio.Main(args);
//LerIdade.Main(args);  
//EleitoresMunicipio.Main(args);
//ExemploIfElseIf.Main(args);
//IfTernario.Main(args);
//Exemplo02IfTernario.Main(args);
//SwitchCaseExemplo01.Main(args);
//MesesDoAnoSwitchCase.Main(args);
//While.Main(args);
//TabuadaDeUmNumero.Main(args);
//SomaDos100PrimeirosNumeros.Main(args);
//SomaDosValoresParesAte500.Main(args);
//DoWhile.Main(args);
//QuadradosDosNumerosInteiros.Main(args);
//SomaNumerosPares.Main(args);
//NumerosDivisiveisPor4.Main(args);
TrigoXadrez.Main(args);
