using System;
using ExerciciosLogica;

//Soma.Main(args);
//Subtracao.Main(args);
//Multiplicacao.Main(args);
//Divisao.Main(args);
//Sucessor.Main(args);
//Antecessor.Main(args);
//Matematica.Main(args);
//Se.Main(args);
//SeSenao.Main(args);
//Retangulo.Main(args);
//Triangulo.Main(args);
//Circulo.Main(args);
//Quadrado.Main(args);
//Losango.Main(args);
//Hexagono.Main(args);
//Trapezio.Main(args);
//ForLoop.Main(args);
//Temporizador.Main(args);
//NumerosAoQuadradoForLoop.Main(args);
//TabuadaDe1A10.Main(args);
//SomaDos100PrimeirosNumerosFor.Main(args);
//SomatórioNumerosParesFor.Main(args);
//ApresentarNumerosImpares1e20.Main(args);
//ApresentarNumerosDivisiveisPor4.Main(args);
PotenciasDe3SemExponenciacao.Main(args);
